version: '2'

services:
  mariadb:
    container_name: LaravelBackend
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=myuser
      - MARIADB_DATABASE=mydatabase
      - MARIADB_PASSWORD=mypassword

  myapp:
    tty: true
    image: bitnami/laravel:5-debian-9
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=myuser
      - DB_DATABASE=mydatabase
      - DB_PASSWORD=mypassword
    depends_on:
      - mariadb
    ports:
      - 8000:3000
    volumes:
      - ./:/app
